terraform-aws-modules/terraform-aws-rds-aurora

README.md
examples/advanced/main.tf
examples/mysql/main.tf
examples/postgresql/main.tf
main.tf
variables.tf

Removed availability_zones var (closes #10)

---

README.md
main.tf
variables.tf

Added support for https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#deletion_protection

Added argument deletion_protection

---

README.md
main.tf
outputs.tf
variables.tf

Add support for database_name argument and output from variable

---

README.md

I never had access to be a maintainer so not much point having me in the README.

Removing myself from README

---

variables.tf

Correct description of replica_scale_min variable

---

README.md

Fix PostgreSQL example link

---

README.md
main.tf
variables.tf

Fixes issue #55 - Aurora Backtrack Mysql

---

README.md
examples/advanced/main.tf
main.tf
outputs.tf
variables.tf

Added ability to deploy a cross region Aurora Cluster Read Replica

---

README.md
main.tf
variables.tf

Add scaling_configuration

---

README.md
examples/mysql/main.tf
main.tf
outputs.tf
variables.tf

Added support for conditional creation of SG and allowed CIDR blocks

---

README.md
main.tf
variables.tf

Allow setting the `iam_roles` parameter on the rds cluster :)

Support setting aws_rds_cluster iam roles

---

README.md
examples/postgresql/main.tf
main.tf
variables.tf

Made description of security group backward compatible (and optional)

---

README.md
examples/postgresql/outputs.tf
main.tf
versions.tf

Practically speaking this is a change that will force changing the password to another random one.
I hope this is not critical and most users will be able to perform this. It does not recreate the database.

Changed random_id to random_password resource

---

main.tf

Disabled special characters in random_password

---

README.md
main.tf
outputs.tf

This allows setting route53 aliases.
I want to set an alias record in route53.
None.
Did not test. It's just a new output.

feat: Add output aws_rds_cluster.this.hosted_zone_id

---

.gitignore
README.md
examples/advanced/outputs.tf
examples/mysql/outputs.tf
examples/serverless/outputs.tf
main.tf
variables.tf

feat: Added conditional creation of RDS Aurora cluster

---

main.tf

fix: Create random_password only when necessary

---

README.md
examples/mysql/main.tf
examples/mysql/versions.tf
main.tf
variables.tf

An incorrect solution was added into #181 
Fixes #183

fix: Create random_password conditionally

---

README.md

- update `README` documentation and reference to license
- repository license is Apache 2.0 not MIT
Closes #163
No
- Doc change only

chore: update `README` documentation and reference to license

---

.releaserc.json
main.tf

- chore: Updated .releaserc config
- chore: Small change in main.tf

chore: Updated .releaserc config and tf file (to trigger release)

---

.releaserc.json
main.tf

- chore: Updated .releaserc config
- chore: Small change in main.tf
- fix: Small useless change in main.tf
- fix: Small useless change in main.tf

fix: Small useless change in main.tf to test semantic-release (last one, I promise)

---

.releaserc.json
main.tf

- chore: Updated .releaserc config
- chore: Small change in main.tf
- fix: Small useless change in main.tf
- fix: Small useless change in main.tf
- fix: Revert small useless change in main.tf

fix: Revert small useless change in main.tf

---

.releaserc.json
main.tf

- chore: Updated .releaserc config
- chore: Small change in main.tf
- fix: Small useless change in main.tf
- fix: Small useless change in main.tf
- fix: Revert small useless change in main.tf
- chore: Giving up on releaserc config (for now)

chore: Giving up on releaserc config (for now)

---

README.md
variables.tf

Typo
Just perusing and noticed it.
None

chore: Correct typo/misspelling

---

main.tf

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/361
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/361
No.

fix: Postgres port conditional adjustment

---

README.md
examples/autoscaling/README.md
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/versions.tf
main.tf
variables.tf
versions.tf

Support for `enable_local_write_forwarding`.
https://github.com/hashicorp/terraform-provider-aws/pull/34370
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-write-forwarding.html#aurora-mysql-write-forwarding-consistency
No.

feat: Support for `enable_local_write_forwarding`

---

README.md
examples/autoscaling/README.md
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/main.tf
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/versions.tf
main.tf
variables.tf
versions.tf

Support `engine_lifecycle_support`. 
https://github.com/hashicorp/terraform-provider-aws/pull/37708
No.

feat: Support `engine_lifecycle_support`
