examples/advanced/main.tf
examples/mysql/main.tf
examples/postgresql/main.tf

This will make the examples run without this error:
```
* module.aurora.aws_security_group_rule.default_ingress: aws_security_group_rule.default_ingress: value of 'count' cannot be computed
```
It's a terraform problem, not a problem with this module. And it's not 100% required since we have `resource.aws_security_group_rule.allow_access` in the example anyway.

Fix for: 'count' cannot be computed

---

main.tf

- No description attr on aws_security_group to avoid forcing new instance on changes
- Use name-prefix to ensure unique names
- For readability: unnecessary name-prefixes

3 adjustments to security group

---

main.tf
variables.tf

Unfortunately Terraform doesn't yet handle this well, we have to hardcode
to be able to pass the list correctly.
Encountered in Terraform 0.11.11
Resolves #11

Hardcode number of allowed_security_groups

---

main.tf
variables.tf

Needed this for an aurora global database setup that I'm working on.

Feature/rds add engine_mode and global_cluster_identifier

---

README.md
examples/advanced/main.tf
examples/mysql/main.tf
examples/postgresql/main.tf
main.tf
variables.tf

Similar to the module [terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds), we should support specifying the variable `vpc_security_group_ids` in case user wish to assign previously created security group on the Aurora cluster. Hopefully this will make the 2 modules more consistent since they tackle the same area of AWS services
I first open this for Terraform 0.11 and if everything is OK I will open a new one for Terraform 0.12 afterward

vpc_security_group_ids for Terraform 0.11

---

README.md
outputs.tf

Adds the ARN of the Aurora Cluster as an output as `this_rds_cluster_arn`.
Fixes: #40

Add cluster ARN output.

---

README.md
examples/mysql/main.tf
main.tf
variables.tf

Allow the addition of IP-based ingress rules

---

README.md
main.tf
variables.tf

Similar to [PR 46](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/46), we would like to support `vpc_security_group_ids` variable in the master branch (for Terraform 0.12.0 and up).

vpc_security_group_ids for Terraform 0.12

---

README.md
main.tf
variables.tf

This feature is useful if RDS resources are imported to Terraform, and changing subnet group in Aurora cluster is not possible without recreating them.

Add support to use existing subnet group name

---

README.md
main.tf
variables.tf

Added variable used to customise predefined metric type 
https://docs.aws.amazon.com/autoscaling/plans/APIReference/API_PredefinedScalingMetricSpecification.html

Add option to customise predefined_metric_type

---

main.tf
outputs.tf

If the `create_security_group` var is set to `false`, then `aws_security_group.this[0]` is not defined, which causes errors (reproduced on terraform v0.12.12):
```
../terraform-aws-rds-aurora/outputs.tf line 57, in output "this_security_group_id":
57:   value       = aws_security_group.this[0].id
|----------------
| aws_security_group.this is empty tuple
```
```
../terraform-aws-rds-aurora/main.tf line 48, in resource "aws_rds_cluster" "this":
48:   vpc_security_group_ids              = compact(concat([aws_security_group.this[0].id], var.vpc_security_group_ids))
|----------------
| aws_security_group.this is empty tuple
```
This PR fixes that in a similar way how it's done in https://github.com/terraform-aws-modules/terraform-aws-vpc

Fix the error when "create_security_group" is set to false

---

README.md
variables.tf

Fixes https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/68
AWS shall automatically pick the right value if none is provided. This works in more cases than with the current ones.

Set null as default parameter

---

README.md
main.tf
variables.tf

This PR adds the option to set the ca_cert_identifier
As the current CA is expiring 5th March 2020 i need to update my clusters to use the new CA before that. The default is currently set to the old one to not break any existing installations.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html
Terraform has recently added support for this. https://github.com/terraform-providers/terraform-provider-aws/pull/10490

add support for ca_cert_identifier option

---

main.tf
outputs.tf

This PR adds name (tag) and description attributes to the security group and its rules.
In addition, to prevent errors when (for example) importing resources with this module present in the configuration, this PR also replaces the hard-coded access to index 0 of conditional resources by a call to `join` function using the splat notation.
An example of the error I was getting while importing resources form other modules, while having this module in my terraform config:
```
Error: Invalid index
on ../../modules/aws-rds-aurora/main.tf line 4, in locals:
4:   db_subnet_group_name = var.db_subnet_group_name == "" ? aws_db_subnet_group.this[0].name : var.db_subnet_group_name
|----------------
| aws_db_subnet_group.this is empty tuple
```

Add security group name and description

---

README.md
main.tf
variables.tf

Reverts terraform-aws-modules/terraform-aws-rds-aurora#83
RDS Aurora does not support ca_cert_identifier.

Revert "add support for ca_cert_identifier option" (fixed v1.20.0)

---

outputs.tf

The password should not be printed to stdout by the cli, since it is
sensitive data.
Hiding sensitive data is a must-have when running Terraform in CD
environments. It is good practice to hide sensitive data from CI/CD logs.
See official Terraform docs for details:
https://www.terraform.io/docs/configuration/outputs.html#sensitive-suppressing-values-in-cli-output

Hide sensitive password data from cli output

---

variables.tf

allowed_security_groups variable is described, and used, as a list so should have the type constraints added

Added missing type type for allowed_security_groups variable

---

main.tf
variables.tf
versions.tf

This PR adds support for the Aurora Serverless Data API added in https://github.com/terraform-providers/terraform-provider-aws/pull/11048.
Fixes #59 
No breaking changes. The default is false, the same as it was when this module wasn't specifying it
I've tested this in my own Terraform stack.
`terraform plan` diff:
```
-/+ resource "aws_rds_cluster" "this" {
...
~ enable_http_endpoint                = false -> true
...
}
```

feat: Support enable_http_endpoint - Data API (#59)

---

README.md
variables.tf

Add support for "multimaster" clusters in documentation
Needed to create a "multimaster" cluster
None
Setting `engine_mode` to "multimaster" creates a new RDS Aurora cluster with multiple writer nodes (limitations applied by AWS on region/instance type/number of instances)

docs: Add "multimaster" to engine_mode docs

---

CHANGELOG.md
main.tf

This PR adds tags to RDS enhanced monitoring IAM role. 
The documentation says:
> tags: A map of tags to add to all resources.
But the tags are not added to the IAM role created for RDS enhanced monitoring. This PR fixes that.
None.
According to the [iam_role](https://www.terraform.io/docs/providers/aws/r/iam_role.html#tags) this should work.

feat: Add tags to RDS enhanced monitoring IAM role

---

.pre-commit-config.yaml
README.md
main.tf
variables.tf

Add support for using an existing IAM role to send RDS enhanced monitoring metrics to CloudWatch Logs.
If the module is used for provisioning multiple clusters in the same account, it will create one monitoring role for each, which isn't really necessary as they're identical - attaching the same AWS managed policy - `AmazonRDSEnhancedMonitoringRole`.
Also, when enabling via the console, from [the docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html#USER_Monitoring.OS.Enabling.Prerequisites):
> The first time that you enable Enhanced Monitoring in the console, you can select the **Default** option for the **Monitoring Role** property to have RDS create the required IAM role. RDS then automatically creates a role named `rds-monitoring-role` for you, and uses …

feat: Add support for existing IAM role for enhanced monitoring

---

CHANGELOG.md
README.md
examples/custom_instance_settings/main.tf
main.tf
variables.tf

Extend PR #132 to allow publicly setting can be set per instance
Sometimes cluster instances can be hidden from public access (let's say writer is private but readers are not), I've combined changes from PR #132 and extend them to control **publicly_accessible** setting per instance.
Doesn't change current setup, old configuration syntax still supported. 
This code from provided example works:
`  instances_parameters = [
// List index should be equal to `replica_count`
// Omitted keys replaced by module defaults
{
instance_type           = "db.r5.2xlarge"
publicly_accessible     = true
},
{
instance_type           = "db.r5.2xlarge"
},
{
instance_name           = "reporting"
instance_type           = "db.r5.large"
instance_promotion_tier = 15
}
]
`

feat: Allow to customizable instance settings

---

main.tf

Updating engine version forces replacement of instances, and they shouldn't be replaced, because cluster will update them if the engine version is changed.
Fixes https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/118
none
I tested this on multiple aurora clusters to upgrade MySQL engine version 2.07.1 -> 2.07.2.

fix: Ignore instance engine version updates

---

README.md
outputs.tf

I have added the engine_version output
context; https://github.com/terraform-providers/terraform-provider-postgresql/issues/2#issuecomment-567887609
This is a helper to the postgres provider, to use its mechanics so there is a way you can instantiate your Aurora postgres instance and use the postgres provider in one run/plan.
No Breaking changes.
I have tested it in my code base, plans now succeed even though the RDS has not been created yet.

feat: add output engine_version to force provider order

---

.pre-commit-config.yaml
README.md
examples/advanced/versions.tf
examples/custom_instance_settings/versions.tf
examples/mysql/versions.tf
examples/postgresql/versions.tf
examples/serverless/versions.tf
main.tf
variables.tf
versions.tf

Exposes the same aws_rds_cluster resource variable as a module variable. Defaults to the same value to preserve backwards compatibility.
see:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#allow_major_version_upgrade

feat: Support major version engine upgrades

---

.gitignore
.pre-commit-config.yaml
README.md

- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A

chore: update documentation based on latest `terraform-docs` which includes module and resource sections

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

- add ci-cd workflow for pre-commit checks
- add `terraform_validate` hook into pre-commit checks
- provide static checks for pull requests
- no
- copy of what is implemented in SQS, Lambda, Autoscaling, etc. module repositories

chore: add ci-cd workflow for pre-commit checks

---

README.md
main.tf
variables.tf

This change adds a new input variable for the module that allows tags to be applied to the RDS cluster only. Existing functionality with the current tags variable is preserved by using a merge of the two maps.
Motivation for adding this new input is that the [AWS Instance Scheduler](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/welcome.html) requires tags be added to the RDS cluster **only** for it to work (i.e. there cannot be a schedule tag added to the RDS instance). Therefore this change is being introduced to allow some tags to specifically be added to the cluster.
No breaking changes. This only introduces one new input variable and merges it into the existing tags on the RDS cluster.
This change has been tested in development and staging environments and works as …

feat: AWS Instance Scheduler Tagging Support

---

README.md
examples/autoscaling/README.md
examples/autoscaling/main.tf
examples/autoscaling/outputs.tf
main.tf
outputs.tf
variables.tf

- add all attributes and some outputs for enhanced monitoring IAM role
- update `autoscaling` example for changes made here
- update variable descriptions (semantic corrects)
- expose all attributes for configuring the enhanced monitoring IAM role
Closes #93
Closes #153 
Closes #196
- Yes - users will need to make the following changes to
```hcl
iam_partition = "aws-gov"
permissions_boundary = "arn:aws:..." -> iam_role_permissions_boundary = "arn:aws:..."
```
- Test/verification stesp:
- Deploy `examples/autoscaling` as currently defined on `master` branch
- Switch to this branch and comment out lines 57-61 of `examples/autoscaling` (+outputs - this is 1:1 compared to what is currently on `master`)
- Run `terraform plan` -> no changes detected
- Uncomment lines 57-61 and outputs
- Run …

chore: add all attributes and some outputs for enhanced monitoring IAM role

---

README.md
versions.tf

Bump required AWS provider version to v3.30
`managed_policy_arns` parameter for the `aws_iam_role` resource was only added in AWS provider v3.29.1. 
Not requiring this minimum version could cause `Unsupported argument` error when the provider is locked to older version.
Not known

fix: Bump AWS provider version

---

examples/serverless/main.tf
main.tf

- when `engine_mode` is `serverless`, set `engine_version` to `null`
Closes #160 
Closes #161
- No
- updated and validated `serverless` example

fix: when `engine_mode` is `serverless`, set `engine_version` to `null`

---

README.md
main.tf
variables.tf

Provide an additional set of tags for the security group created
Needed for enterprise security audits
None
- Verified that providing this value does tag the security group correctly.
- Works like cluster_tags

feat: Additional tags for security group

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

.github/workflows/pre-commit.yml
README.md
variables.tf

This boolean doesn't indicate if a final snapshot should be taken but
rather it taking that snapshot should be skipped. I just hijacked the
language from the resource documentation.
The change is not required, but it is an improvement in clarity, I believe.
none
Only documentation was changes.

docs: Clarify description of skip_final_snapshot variable

---

.pre-commit-config.yaml
main.tf

- set backup and maintenance windows to `null` when using serverless mode
- Closes #167
- No
- validated using serverless example

fix: set backup and maintenance windows to `null` when using serverless mode

---

.pre-commit-config.yaml
README.md
examples/autoscaling/outputs.tf
examples/custom_instance_settings/outputs.tf
examples/mysql/outputs.tf
examples/postgresql/outputs.tf
examples/s3_import/outputs.tf
examples/serverless/outputs.tf
outputs.tf

- mark sensitive outputs to support Terraform 0.15.x
- Closes #212
- No
- Tested on `examples/postgresql` and checked with just plans on remaining examples

fix: mark sensitive outputs to support Terraform 0.15.x

---

README.md
examples/mysql/README.md
examples/mysql/outputs.tf
examples/postgresql/README.md
examples/postgresql/outputs.tf
outputs.tf

- add output for cluster instance `db_resource_id` output list
Closes #217 
- No
- Updated `mysql` and `postgresql` examples and validated using `postgresql`
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
rds_cluster_database_name =
rds_cluster_endpoint = postgresql.cluster-c9zyrpwvxzzr.eu-west-1.rds.amazonaws.com
rds_cluster_id = postgresql
rds_cluster_instance_dbi_resource_ids = [
"db-J42FV3T47NUY2AFIWGZVF6BOMU",
"db-DWKBTBWO7MIKOHVPALLNAYS6D4",
]
rds_cluster_instance_endpoints = [
"postgresql-1.c9zyrpwvxzzr.eu-west-1.rds.amazonaws.com",
"postgresql-2.c9zyrpwvxzzr.eu-west-1.rds.amazonaws.com",
]
rds_cluster_instance_ids = [
"postgresql-1",
"postgresql-2",
]
rds_cluster_master_password = <sensitive>
rds_cluster_master_username = <sensitive>
rds_cluster_port = …
```

chore: add output for cluster instance `db_resource_id` output list

---

.pre-commit-config.yaml
README.md
examples/postgresql/main.tf
main.tf
variables.tf

- update pre-commit hook versions and URI for HTTPS
- fix links in README by using full URL links instead of relative (closes #38)
- add egress security group rule with new variable to map multiple rules for egress (closes #248)
- fixed small bug in port local variable logic: during last breaking change the `var.part` default value changed from `""` to `null`. this change makes the local variable logic work as intended with the new default value
Closes #38 
Closes #248 
- No
- tested with the `examples/postgresql` example project

feat: Add security group egress rule support, fix documentation links

---

UPGRADE-6.0.md

Change reference to `instance_type` to `instance_class`
Change incorrect references to `instance_type` in the upgrade to 6 notes
The documentation was misleading as copied it and ran into errors, updated the documentation to reflect correct API
None - purely documentation
N/A

chore: Update error in UPGRADE-6.0md

---

main.tf

add `create_before_destroy` to the SecurityGroup resource
This fixes AWS API timeouts/errors when changing the name, name_prefix, or description, as described in the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#change-of-name-or-name-prefix-value)

fix: SecurityGroup - create_before_destroy

---

examples/mysql/main.tf

…rora-mysql" issue. per antonbabenko's suggestion changed engine_version to just major.minor version. "5.7.mysql_aurora.2.10.1" also works

fix: InvalidParameterCombination: Cannot find version 5.7.12 for aurora-mysql

---

README.md
main.tf
variables.tf

- Correct DB instance parameter group used when users do not create one nor provide the name of existing, will use default
- Ref #319 
- Ref #320
- No

fix: Correct DB instance parameter group used when users do not create one nor provide the name of existing, will use default

---

README.md
main.tf
variables.tf
versions.tf

Add support for the network_type argument.
I've got RDS clusters in production that need to be deployed in dual-stack mode, and this module didn't support that configuration yet. Instead of maintaining a private fork, I will submit a patch.
The required AWS provider is bumped from 4.6 to 4.28. This version is where the network_type argument became available.

feat: Add support for network_type argument

---

UPGRADE-6.0.md

I believe that this should be` } `and not `]`
Read that while tryng to follow the docs of the migration to v6.

docs: Correct typo in `UPGRADE-6.0.md`

---

.github/workflows/release.yml

The `Release` workflow are using an old version and hence a [deprecated runtime (Node.js 12)](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Bumping this workflow will resolve the deprecation warning in the affected workflow.
Make sure that CI workflows uses non-deprecated runtimes.
None.

chore: Upgrade CI workflow to use non-deprecated runtime

---

main.tf

Use the create_before_destroy lifecycle setting for the parameter groups so that major version updates are possible.
It enables major version upgrades.
It fixes: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/353
No breaking changes.

fix: Use `create_before_destroy` lifecycle on parameter groups to support major version upgrades

---

.pre-commit-config.yaml
main.tf

- Allow setting `master_username` when using `manage_master_user_password`
- Resolves #368
- No

fix: Allow setting `master_username` when using `manage_master_user_password`

---

README.md
main.tf
variables.tf

I have a scenario where I would like the security group name to be different. The RDS is called after the service, e.g. `myapp-staging`. I would like the security group to be named `myapp-staging-rds`. This change will allow to customise the security group name while keeping backwards compatiblity.
fixes #376
I have multiple security groups, each with a prefix:
* `myapp-staging-default`
* `myapp-staging-rds-proxy`
* `myapp-staging-lambda-app`
* ...
The only security group not matching this schema is created by the `terraform-aws-rds-aurora` module.
None.

feat: Ability to set custom `security_group_name`

---

main.tf

The introduction of `security_group_name` (#376) missed the adjustment of the `Name` tag for the security group. This rectifies this issue.
Consistency and correctness.
None.

fix: Tag security group with correct name

---

README.md
examples/autoscaling/README.md
examples/autoscaling/main.tf
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/main.tf
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/main.tf
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/main.tf
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/main.tf
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/main.tf
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/main.tf
examples/serverless/versions.tf
versions.tf

- upgrade aws provider version to address https://github.com/hashicorp/terraform-provider-aws/pull/31336
- add example for aurora I/O optimized - https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/381
- update example with `master_username` since [default is now null](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/89b540474f4e20b2029989e3558eedfaeedb47b3/variables.tf#LL216C1-L216C1) but it's still required if `is_primary` is `true`
- update example for serverless to address `InvalidParameterValue: The parameter ManageMasterUserPassword is not valid for engine mode: serverless.`
- https://github.com/hashicorp/terraform-provider-aws/pull/31336
- Resolves #381
- fixes example errors `InvalidParameterValue: The parameter MasterUsername must be …

feat: Upgrade aws provider version and update examples

---

.pre-commit-config.yaml
README.md
examples/autoscaling/README.md
examples/autoscaling/main.tf
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/main.tf
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/main.tf
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/main.tf
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/main.tf
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/main.tf
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/main.tf
versions.tf

Loosen version constraint for AWS provider. Currently major version is pinned to 4. This change allows using newer major version, like the just released version 5.
I want to upgrade my workspaces using this module to AWS provider version 5.
Solves issue #384.
No breaking change found.

feat: Enable support for v5.0 of the AWS provider

---

main.tf

The changes pass the missing tags to `aws_appautoscaling_target`.

fix: Tag Application AutoScaling target

---

README.md
variables.tf

This PR updates the documentation for the `storage_type` input variable, as the usage of the [relatively new Aurora I/O Optimized](https://aws.amazon.com/blogs/aws/new-amazon-aurora-i-o-optimized-cluster-configuration-with-up-to-40-cost-savings-for-i-o-intensive-applications/) storage type wasn't covered by the documentation of this module.
Came across Aurora I/O Optimized and tried looking for information on how to configure it with this module. [One of the examples](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/7eec8f4db8f94441e12f961c926820ea6fce1bb7/examples/postgresql/main.tf#L32) actually uses the relevant storage type `aurora-iopt1`, but the option was undocumented.
Relevant references:
- [AWS Terraform provider RDS cluster resource: `storage …

docs: Update storage_type docs entry to mention I/O Optimized storage configuration

---

examples/postgresql/main.tf
main.tf

Enable to set `db_parameter_group_name` attribute per replica.
Now, we can set `db_parameter_group_name` just in the whole cluster level. We need the ability to set it per instance.
No breaking changes.

feat: Enable db_parameter_group_name per instance

---

README.md
examples/global-cluster/main.tf
examples/mysql/README.md
examples/mysql/main.tf
examples/mysql/outputs.tf
examples/postgresql/README.md
examples/postgresql/main.tf
examples/postgresql/outputs.tf
main.tf
outputs.tf
variables.tf

Closes: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/404
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/404
No.

feat: Add RDS cluster activity stream 

---

examples/serverless/main.tf
main.tf

AWS added support for configuring maintenance windows on Serverless V1 clusters in February 2023, as described in [this announcement](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-aurora-serverless-v1-configurable-maintenance-windows/). The terraform-aws-rds-aurora module does not pass the preferred_maintenance_window argument down to the aws_rds_cluster resource if engine_mode is serverless.
This change was done in the context of this issue [213](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/213)
Note:
Also tested to set the `preferred_backup_window` attribute on serverless, but it still gives the error:
`InvalidParameterCombination: You currently can't modify BackupWindow with Aurora Serverless`
We cannot warn our customers of database maintenance …

fix: Allow Serverless maintenance windows

---

.pre-commit-config.yaml
CHANGELOG.md
main.tf
variables.tf

see https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/430
Fixes perpetual drift in `aws_appautoscaling_target` on clusters created before 2023-03-30, see [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target)
- Resolves #430 
None

fix: Ignore `tags_all` for `aws_appautoscaling_target`

---

.pre-commit-config.yaml
main.tf

- Do not create dynamic DNS suffix for service principals
- Resolves #437 
- No

fix: Do not create dynamic DNS suffix for service principals

---

examples/postgresql/main.tf

Specify type as egress for security group rules in postgresql egress example
Correct security_group_rules example to specify type = "egress" for egress rules.
By default the type is ingress, while for egress rule it's required to explicitly specify the type.
No.

docs: Specify type as egress for security group rules in example

---

README.md
examples/autoscaling/README.md
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/main.tf
examples/serverless/versions.tf
main.tf
versions.tf

Support `scaling_configuration.seconds_before_timeout` in Aurora Serverless V1.
https://github.com/hashicorp/terraform-provider-aws/pull/38451
No.

feat: Support for `scaling_configuration.seconds_before_timeout` in Serverless V1

---

main.tf

When using the same security group alongside an RDS proxy, it is required to have self references
When using the same security group alongside an RDS proxy, it is required to have self references
No

feat: Add "self" attribute to the security group rule

---

README.md
examples/autoscaling/README.md
examples/autoscaling/versions.tf
examples/global-cluster/README.md
examples/global-cluster/versions.tf
examples/multi-az/README.md
examples/multi-az/versions.tf
examples/mysql/README.md
examples/mysql/versions.tf
examples/postgresql/README.md
examples/postgresql/versions.tf
examples/s3-import/README.md
examples/s3-import/versions.tf
examples/serverless/README.md
examples/serverless/main.tf
examples/serverless/versions.tf
versions.tf

Bump aws provider version to include bugfix for `enable_http_endpoint` to be enabled and disabled for provisioned engine mode and serverlessv2.
https://github.com/hashicorp/terraform-provider-aws/pull/38997
Closes: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/464
No.

fix: AWS provider bump for bugfix on `enable_http_endpoint`

---

.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/autoscaling/README.md
examples/global-cluster/README.md
examples/multi-az/README.md
examples/mysql/README.md
examples/postgresql/README.md
examples/s3-import/README.md
examples/serverless/README.md

- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No

fix: Update CI workflow versions to latest

---

main.tf

Add a `create_before_destroy` lifecycle block to the `aws_rds_cluster_instance` resources.
This improves time to recover in the (uncommon) case where the DB instances have to be replaced, for example to change their identifier or network configuration. We have observed that it can take nearly 10 minutes to destroy an Aurora instance. And then a similar time to create its replacement. During this time the DB is inaccessible. By using `create_before_destroy`, there is only a small interruption while one of the new instances is promoted to the Writer role. Which seems to typically take less than 30 seconds. 
N/A
There is nothing to change in the `examples`, everything is internal to the code of the module.

feat: Add `create_before_destroy` to Aurora DB instance resource
